import 'dart:math';

class TestResponse {
  final Map<String, dynamic> accountInfo = {
    "balance": Random().nextDouble() * 1500,
    "transactions": transactionResponse,
    "registration_date": "2022-10-17T03:19:25",
  };

  static const List<Map<String, dynamic>> transactionResponse = [
    {
      "id": 1,
      "name": "IKEA",
      "transaction_type": 'credit',
      "amount": 85.90,
      "overview": "You buy chair",
      "transaction_time": "2022-10-17T03:19:25",
      "is_pending": true,
      "name_sender": null,
      "cashback": 0.02,
    },
    {
      "id": 2,
      "name": null,
      "transaction_type": 'payment',
      "amount": 200.00,
      "overview": "This your salary",
      "transaction_time": "2022-09-17T03:19:25",
      "is_pending": false,
      "name_sender": null,
    },
    {
      "id": 3,
      "name": 'Apple',
      "transaction_type": 'credit',
      "amount": 85.90,
      "overview": "Card number user",
      "transaction_time": "2022-10-17T03:19:25",
      "is_pending": true,
      "name_sender": "Diana",
      "cashback": 0.03,
    },
    {
      "id": 4,
      "name": null,
      "transaction_type": 'payment',
      "amount": 92.35,
      "overview": "From JP Morgan Chase Bank National",
      "transaction_time": "2022-10-18T03:19:25",
      "is_pending": false,
      "name_sender": null,
    },
    {
      "id": 5,
      "name": null,
      "transaction_type": 'payment',
      "amount": 73.58,
      "overview": "From JP Morgan Chase Bank National",
      "transaction_time": "2022-10-18T03:19:25",
      "is_pending": false,
      "name_sender": null,
    },
    {
      "id": 6,
      "name": 'Target',
      "transaction_type": 'credit',
      "amount": 123.90,
      "overview": "Some information",
      "transaction_time": "2022-10-12T03:19:25",
      "is_pending": false,
      "name_sender": null,
      "cashback": 0.02,
    },
    {
      "id": 7,
      "name": 'Target',
      "transaction_type": 'credit',
      "amount": 249.90,
      "overview": "Some information",
      "transaction_time": "2022-08-12T03:19:25",
      "is_pending": false,
      "name_sender": null,
      "cashback": 0.02,
    },
    {
      "id": 8,
      "name": 'Apple',
      "transaction_type": 'credit',
      "amount": 85.90,
      "overview": "Card number user",
      "transaction_time": "2022-10-17T03:19:25",
      "is_pending": true,
      "name_sender": "Diana",
      "cashback": 0.03,
    },
    {
      "id": 9,
      "name": 'IKEA',
      "transaction_type": 'credit',
      "amount": 29.90,
      "overview": "Some information",
      "transaction_time": "2022-03-17T03:19:25",
      "is_pending": false,
      "name_sender": null,
    },
    {
      "id": 10,
      "name": 'IKEA',
      "transaction_type": 'credit',
      "amount": 15.90,
      "overview": "Some information",
      "transaction_time": "2022-10-19T03:19:25",
      "is_pending": false,
      "name_sender": null,
    },
  ];
}
